baseURL = "https://omurturan.com"
languageCode = "tr"
DefaultContentLanguage = "tr"
title = "Home"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "ğŸ‘¨â€ğŸ’»ğŸ¹â˜•ï¸ğŸŒ»ğŸ––"
author = "Ã¶mÃ¼r"
description = """
Veli Ã–mÃ¼r Turan
"""
profilePicture = "images/profile.jpg"
keywords = "Veli Ã–mÃ¼r Turan"
favicon = "favicons/"
mainSections = ["posts"]
doNotLoadAnimations = true
readMore = true
# displayMode = "dark"
disableThemeSwitcher = true
enableMediumZoom = false

customCss = ["css/custom.css"]

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://twitter.com/omurturan"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/omurturan/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/omurturan"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://instagram.com/omurturan"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:info@omurturan.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 300
  identifier = "contact"
  url = "/contact/"

[markup.goldmark.renderer]
unsafe= true
